import { Injectable } from '@angular/core';
import{Http} from '@angular/http';
import { Headers,Response } from '@angular/http';
import 'rxjs/Rx';

import { Observable } from 'rxjs/Observable';
import  'rxjs';

@Injectable()
export class AuthServiceService {

  constructor(private http:Http) { }



  //functions
  //signup
  signup(username:string,email:string,password:string)
  {

     /*return
     take 3 parameters:- 
      1-URL
      2-The data coming
      3-the type of data coming*/
   return this.http.post('http://localhost/project/public/api/client',{
      name:username,email:email,password:password},
  {headers:new Headers({'X-Requested-With':'XMLHttpRequest'})});

   
  }

  //signin for clients
  signin(email:string,password:string)
  {
    return this.http.post('http://localhost/project/public/api/client/signin',{
     email:email,password:password},
  {headers:new Headers({'X-Requested-With':'XMLHttpRequest'})})
  .map(
    (response:Response)=>{
      const token=response.json().token;
      const base64Url=token.split('.')[1];
      const base64=base64Url.replace('-','+').replace('_','/');
      return {token: token,decoded:JSON.parse(window.atob(base64))};
    }
  ).do(
    tokenData=>{
      //Saving the token that generated by JWT in localeStorage
      localStorage.setItem('token',tokenData.token);
      
    },
    role=>{
      localStorage.setItem('role',role.decoded.role);
    }                
  );

  }
//get the current token
  getToken()
  {
    return localStorage.getItem('token');
  }

  //get the current Role
  getRole()
  {
    return localStorage.getItem('role');
  }


}
